apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  labels:
    managed-by: mogenius
    mogenius-helm-repo-name: podinfo
spec:
  revisionHistoryLimit: 1
  destination:
    name: homelab
    namespace: radicale-test
  syncPolicy:
    automated:
      prune: true
      enabled: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: k8s-platform
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.14.0
    chart: podinfo
    helm:
      releaseName: podinfo
      valuesObject: null
