apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radicale-mogenius-test
  namespace: argocd
  labels:
    managed-by: mogenius
    mogenius-helm-repo-name: own
spec:
  revisionHistoryLimit: 1
  destination:
    name: homelab
    namespace: radicale-test
  syncPolicy:
    automated:
      prune: true
      enabled: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: k8s-platform
  source:
    repoURL: https://charts.derwitt.dev
    targetRevision: 2.1.0
    chart: radicale
    helm:
      releaseName: radicale-mogenius-test
      valuesObject: null
